version: 1.2
workflows:
   - name: ctat-mutations-DV
     subclass: WDL
     primaryDescriptorPath: /WDL/ctat-mutations-DV.wdl
     authors:
         - name: Brian Haas
           email: bhaas@broadinstitute.org
   - name: hg19_ctat-mutations-DV
     subclass: WDL
     primaryDescriptorPath: /WDL/Terra/ctat-mutations-DV.Terra.hg19.wdl
     authors:
         - name: Brian Haas
           email: bhaas@broadinstitute.org
   - name: hg38_ctat-mutations-DV
     subclass: WDL
     primaryDescriptorPath: /WDL/Terra/ctat-mutations-DV.Terra.hg38.wdl
     authors:
         - name: Brian Haas
           email: bhaas@broadinstitute.org
